### PR TITLE
Create Address planning session.

### PR DESCRIPTION
**Pull request by joaolucasmacedo**
Hi @becarpenter .
Please review it.

### CODE REVIEW

**Comment by buraglio** [comment]
Thanks, this is great. I think we also want to talk a bit about shifting left as a general rule since most very large sites are now receiving substantially more than a /32 and we may want to address that. RFC 6177 is fairly dated at this point, and while not prescriptive, it could probably use a refresh, or at least a quick revisit.  I will wait to merge until Brian has seen it, but it looks like a solid start to me. Thoughts on adding some text on use of IPAM for ease of management?

**Comment by becarpenter** [comment]
Time permitting I will merge this PR later today (NZ time) and then do a little grammar editing on the main branch. I can also expand a bit on the IPv5 (and IPv7) story. I wil _not_ mention IPv10 :-).

We also need a section on address planning within an enterprise or campus, and we need somebody with experience to write about APAM systems that support IPv6.

**Comment by buraglio** [comment]
It would be remiss of us to not mention Tom Coffeen's book on IPv6 address planning. It has been the de facto standard for quite some time and is very comprehensive.

**Comment by joaolucasmacedo** [comment]
> Time permitting I will merge this PR later today (NZ time) and then do a little grammar editing on the main branch. I can also expand a bit on the IPv5 (and IPv7) story. I will _not_ mention IPv10 :-).
> 
> We also need a section on address planning within an enterprise or campus, and we need somebody with experience to write about IPAM systems that support IPv6.

Hi Brian. Thanks for your comment. Well I'm about to translate my article on IPv5. I wrote it some time ago partially based on a chapter of you book. I'd love to see you comment and contribution.  Also would like to see the comments from @bobhinden  
It is kinda fun about the Kobe incident... Can't wait to see you thoughts on IPv7 and IPv10.

About the IPAM, answering both you and @buraglio, you are lucky. I'm a active advocate for Netbox, a popular IPAM and Source of Truth. I can think something to write about regarding IPv6. Ideas are welcome.

Would you like to open a discussion for it?

**Comment by joaolucasmacedo** [comment]
> Thanks, this is great. I think we also want to talk a bit about shifting left as a general rule since most very large sites are now receiving substantially more than a /32 and we may want to address that. RFC 6177 is fairly dated at this point, and while not prescriptive, it could probably use a refresh, or at least a quick revisit. I will wait to merge until Brian has seen it, but it looks like a solid start to me. Thoughts on adding some text on use of IPAM for ease of management?

Thanks @buraglio ! Yes, and I'm a active user of Netbox IPAM. Please be welcome to review and add things on this piece.

**Comment by buraglio** [comment]
Perfect. I think I have enough background to give it a good review. Thanks again for contributing!

**Comment by becarpenter** [comment]
I merged the PR and did some minor edits on the main branch. RENAMED one file because apparently "?" in filenames is not allowed by GitHub (nor by WIndows??). That's it for today.

**Pull request merged**
